### ISSUE TITLE
request: bulk add/admin with json structure

### ISSUE THREAD

**Issue by btmurrell** [karol-121/custom-context-menu-search#12]
it would be nice to have a bulk mode in some data format such as json or yaml. this would allow for export/import to other browser instances, such as different firefox profiles, different computers, or sharing w/ a friend.

**Comment by karol-121** [comment]
Implemented in commit 0fb9440fa811a2f93f524f616dc1d060fb417041

**Comment by btmurrell** [comment]
this is awesome. thank you so much @karol-121  for the quick feature add. 🚀 works great!
